export const GOOGLE_WEB_CLIENT_ID =
    process.env.EXPO_PUBLIC_YOUR_WEB_CLIENT_ID_FROM_GOOGLE_CLOUD_CONSOLE;
//    process.env.EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID; dev
export const GOOGLE_IOS_CLIENT_ID =
    process.env.EXPO_PUBLIC_GOOGLE_IOS_CLIENT_ID;
